spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shortify
      username: root
      password: pass
      authentication-database: admin
      auto-index-creation: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    cache: false

shortify:
  short-url:
    length: 10
    hash-salt: 39357235fb2579f9d8ebecf979f906f0
    max-attempts: 10
    expiration-days: 360
    inactive-days: 90
  scheduler:
    thread-pool-size: 5
    cleanup-rate: 1800000