spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shortify
      username: root
      password: pass
      authentication-database: admin
      auto-index-creation: true

shortify:
  url:
    short-url:
      length: 10
      hash-salt: "EKWEJLERDIWJLJIMCVOEOEIOGNIOWOPKDFWOMWINF"
      max-attempts: 10
      expiration-days: 360
      inactive-days: 90
    scheduler:
      thread-pool-size: 5
      cleanup-rate: 1800000